christianhaitian/PortMaster

- PortMaster/control.txt
Added $HOTKEY parameter for use in gptokeyb to allow override of hotkey used for quick exit. Used by adding command line to gptokey '-hotkey <button_name>' where button_name is short code used by gptokeyb to assign key functions https://github.com/romadu/gptokeyb/blob/4290b435bd747eb4b9a9dfe7ae3cedfc0cb83d16/gptokeyb.cpp#L150, noting that currently only l3 (L3) has been activated for hotkey override https://github.com/romadu/gptokeyb/blob/4290b435bd747eb4b9a9dfe7ae3cedfc0cb83d16/gptokeyb.cpp#L778. Other buttons can be activated if required, but a hotkey button will need to have been assigned an SDL_CONTROLLERBUTTON function to be available for use as a hotkey.
> Added $HOTKEY parameter for quick exit override in gptokeyb

- PortMaster/control.txt
requiring alternative hotkey assignment for quick exit in gptokeyb; called by including '-hotkey <button_name>' where button_name are short-form button names used by gptokeyb https://github.com/romadu/gptokeyb/blob/4290b435bd747eb4b9a9dfe7ae3cedfc0cb83d16/gptokeyb.cpp#L141 noting that currently only l3 (L3) has been configured for hotkey use in addition to Back and Guide. Other buttons can be added as needed. https://github.com/romadu/gptokeyb/blob/4290b435bd747eb4b9a9dfe7ae3cedfc0cb83d16/gptokeyb.cpp#L778
> Added $HOTKEY for use with Chi and devices

- .github/workflows/sync.yml
New GitHub Actions logic run on commit:
- Clone repo for zips less than 100mb
- Fetch 'large' files release for zips greater than 100mb+ (SuperTux, UQM, srb2kart, srb2).
-  The 'large-files' GitHub Release is here for now: https://github.com/pkegg/PortMaster-Hosting/releases/tag/large-files.  NOTE: this release is manually created/updated similar to how china server is manually updated today.
- Sync all above files to china server.
This makes is so that the china server is just a 'mirror' of what's in the GitHub repository (+ large files which are also in GitHub).  Having everything come from GitHub is advantageous for future GitHub build automation (and is simpler than existing process in the mean time).
Mostly for: @christianhaitian / @romadu
- After this change, updating the china …
> Add rsync to china server on commit

- ports.md
Wiki text:
Doom 3 (RG552 Only) (Available through PortMaster)
Instructions: You need to add your own full game pak files to the ports/doom3/base folder. Then you should be able to launch Doom3 from Ports in the emulationStation menu.
Notes: Thanks to Gabriel Cuvillier (https://github.com/gabrielcuvillier/d3wasm) for the d3wasm engine. Also thanks to brooksytech for the porting and packaging for portmaster.
> Add Doom 3 to portmaster. RG552 only. 

- PortMaster/control.txt
- PortMaster/tasksetter.sh
This PR might require a bit more testing - specially the `$ESUDO` change.
On RetroOZ, `/dev/uinput/` is a priviledged file, elevating `gptokeyb` instances fixes issues with missing inputs on releases using gptokeyb and on the main PortMaster script.
Also provided on this PR is the `tasksetter.sh` helper script, so that `taskset` can be used without needing hardcoded presets, and with a healthy amount of sanity checks, this is more experimental but has been working for at least a few weeks in a variety of ports for me so far.
> RetroOZ permission fixes and tasksetter.sh.

- PortMaster/control.txt
Hi Christian,
Please, permiteme enviarte este PR que permite corregir la integracion de PortMaster con RetroOz.
With the last changes/updates of RetroOz, really, the MAX2 devices are the same as a MAX device.
Also, in RetroOz you can change the position of the buttons "select" and "start", then you need more changes on the "gamecontrollerdb.txt" file.
Bye and great work.
> Rigth Integration of MAX/MAX2 devices with RetroOz

- ports.md
This adds a port for Shipwreck by Brushfire Games. It is a Zelda-like game made with FNA that is available on itch.io and has been included in many bundles. This is my first time contributing, let me know if anything needs to change. I have tested through the first dungeon on a 552 running Amberelec and a 351v running Arkos.
> Add Shipwreck port

- ports.md
Tile World is a source port clone of "Chip's Challenge", which originated on the Atari Lynx.
To play the original Chip's Challenge levels, copy your "chips.dat" into 'ports/tileworld/data' and make sure it's lowercase.
This was possible by modifying the SDL2 conversion of TileWorld from https://github.com/rangeli/tileworld.
This currently runs on RG351P, RG351M, RG351MP and RG351V running ArkOS or 351Elec/AmberElec.
It may run on some of the other very similar handhelds and other OSes as well, but this has yet to be tried on those configurations.
> Add Tile World

- ports.md
The large binary blobs for the larger games (Sonic Robo Blast 2, Sonic RB2 Kart, etc) have been moved from a Chinese server to GitHub. This change removes the language from the UI mentioning the old server.
> Clarify server location for large ports as it has been moved from china to GitHub

- ports.md
Wiki entry:
Bugdom
Instructions: Bugdom files are already included and ready to go. Just start Bugdom from Ports in the emulationstation menu. Use the touchscreen to navigate the UI. Currently only runs on the RG552 with Jelos installed. 
Notes: Thanks to Pangea Software for creating the game and publicly releasing the game files. Thanks to Jorio for porting the game engine to various platforms. https://github.com/jorio/Bugdom
> Add bugdom port for JELOS -> 552

- ports.md
Wiki entry:
Billy Frontier (RG552 JelOS Only!)
Instructions: Billy Frontier files are already included and ready to go. Just start Billy Frontier from Ports in the emulationstation menu. Use the touchscreen to navigate the U and some gameplay. Currently only runs on the RG552 with Jelos installed.
Notes: Thanks to Pangea Software for creating the game and publicly releasing the game files. Thanks to [Jorio](https://github.com/jorio/BillyFrontier) for porting the game engine to various platforms. Also thanks to brooksytech for the porting work for portmaster.
> Billy Frontier

- ports.md
Hexen II is a dark fantasy 1st-person shooter developed by Raven Software and published by id software.  Portal of Praevus features new levels, new enemies and a new playable character class, The Demoness.  The Hexen II pak0.pak and pak1.pak data files are required for Hexen 2 and pak3.pak is required to play the Portal of Praevus expansion.
This should run on RG351P, RG351M, RG351MP, and RG503 running ArkOS or 351Elec/AmberElec (and likely other devices and OSes).
> Add Hexen 2 and Portal of Praevus

- ports.md
To play **Half-Life** you need to copy over the contents of the `valve` directory from your steam install of [Half-Life](https://store.steampowered.com/app/70/HalfLife/) info `ports/Half-Life/valve`, on first run it will override the required files to run.
To play **Half-Life: Blue Shift** you need to have Half-Life installed, then copy over the contents of the `bshift` directory from your steam install of [Half-Life: Blue Shift](https://store.steampowered.com/app/130/HalfLife_Blue_Shift/) info `ports/Half-Life/bshift`, on first run it will override the required files to run, and create a `Half-Life Blue Shift.sh` in your ports directory.
To play **Half-Life: Opposing Forces** you need to have Half-Life installed, then copy over the contents of the `gearbox` directory from your steam …
> Added Half-Life port.

- ports.md
To play various Rlvm compatible Visual Novels you need to copy over the game files into `ports/rlvm/games` into their own directory. For example you would install the **CLANNAD** game files into `ports/rlvm/games/CLANNAD` directory. HD versions do not currently work correctly, nor does it work correctly on the RG351P/M devices. For better font compatibility add your own copy of `msgothic.ttc` into `ports/rlvm/fonts`.
[Rlvm](https://github.com/eglaysher/rlvm) is a RealLive interpreter to run Visual Novels by Key. Lots of small tweaks were required to get the engine to run. Fixes wee required for the font loading system, save locations, and fixes for the SDL_image code. This port also uses [gl4es](https://github.com/ptitSeb/gl4es), [sdl12-compat](https://github.com/libsdl-org/sdl12-compat), …
> Added Rlvm port.

- PortMaster/PortMaster.sh
I noticed this bug when I tried downloading Ports to my 353V with TF2 enabled and Portmaster would download them however it didn't download to my Portmaster folder in roms2.
Before, the roms2 was being passed as a file path (or command?) instead of a string.
This was causing Portmaster to always attempt to download in "roms" root directory, as the if statement would always be false. 
Before PR: We would get `roms2: not found` regardless if that is false. 
After the PR: The if statement will now correctly check for roms2. 
Now Portmaster will download to roms2 as expected if you have TF2 enabled. 
Tested on latest ArkOS on 353V
> [Bug Fix] Fixed ROMS2 Dir not being detected.

- ports.md
[OpenRCT2](https://github.com/OpenRCT2/OpenRCT2) is an open-source re-implementation of RollerCoaster Tycoon 2, a construction and management simulation video game that simulates amusement park management.
OpenRCT2 requires original files of RollerCoaster Tycoon 2 to play. It can be bought at either [Steam](https://store.steampowered.com/app/285330/) or [GOG.com](https://www.gog.com/game/rollercoaster_tycoon_2). If you have the original RollerCoaster Tycoon and its expansion packs, you can point OpenRCT2 to these in order to play the original scenarios.
Install your Roller Coaster Tycoon 2 game files into `{PORTS}/openrct2/RCT2`, **these files are required**, and optionally your Roller Coaster Tycoon 1 game files into `{PORTS}/openrct2/RCT1`.
For help getting the game files for [RCT2 on …
> Added OpenRCT2.

- ports.md
[Augustus](https://github.com/Keriew/augustus) is an open-source re-implementation of Caeser III a city-building simulation game developed by Impressions Games and published by Sierra On-Line in 1998. It is the third installment in the Caesar series and is set in ancient Rome.
Augustus  will not run without the original Caesar 3 files. You can buy a digital copy from GOG or Steam, or you can use an original CD-ROM version.
Install the game files into `ports/augustus/data`, here are some excellent instructions [from the Julius project](https://github.com/bvschaik/julius/wiki/Running-Julius) (which Augustus is a fork of). If installing from the CD's you'll need to get the [latest patches](https://github.com/bvschaik/julius/wiki/Patches).
This currently has been verified to run on on …
> Added Augustus.

- ports.md
[VCMI](https://github.com/vcmi/vcmi) is work-in-progress attempt to recreate engine for Heroes III, giving it new and extended possibilities.
VCMI will automatically copy and extract the required game files, you can either install from CD1 & CD2, GoG or an installed copy of the game. This requires about 2-3 gb of free space.
For the **gog version** copy `setup_heroes_of_might_and_magic_3_complete_4.0_(28740)-1.bin` and `setup_heroes_of_might_and_magic_3_complete_4.0_(28740).exe` into `ports/vcmi`.
For the **cd version** copy the contents of **cd1** into `ports/vcmi/cd1` and **cd2** into `ports/vcmi/cd2`.
For the **installed version** copy installed game files into `ports/vcmi/install`.
So far I have only reliably tested the GoG version, so your mileage may vary.
This currently has been …
> Added VCMI

- ports.md
[Open Fodder](https://github.com/OpenFodder/openfodder) is an open source version of the Cannon Fodder engine, for modern operating systems.
Cannon Fodder is an action-strategy shoot 'em up game developed by Sensible Software and published by Virgin Interactive.
The game is military-themed and based on shooting action but with a strategy game-style control system. The player directs troops through numerous missions, battling enemy infantry, vehicles and installations.
The game comes with demo files, to install the full versions:
Copy `CF_ENG.DAT` from the CD (or the GOG install destination) to the `roms/openfodder/Data/Dos_CD` folder.
See [here](https://github.com/OpenFodder/openfodder/blob/master/INSTALL.md#amiga) for details on doing so.
This currently has been verified to run on on …
> Added OpenFodder, Updated Half-Life, VanillaRA, and VanillaTD

- ports.md
Removed the . in Tiny Crate and added a new Port for Titan Tactics
Titan Tactics
Instructions: Titan Tactics files are already included and ready to go. Just start Titan Tactics from Ports in the Emulationstation menu.
Notes: Thanks to Team Potato (https://gitlab.com/team-potato/titan_tactics)  for creating this game and making available for free and efornara for creating the FRT platform. Also thanks to Cebion for the packaging for portmaster.
> Add Titan Tactics / Fix typo in TinyCrate

- ports.md
New Port for Pekka Kana 2
Pekka Kana 2
Instructions: Pekka Kana 2 files are already included and ready to go. Just start Pekka Kana 2 from Ports in the Emulationstation menu.
Notes: Thanks to Janne Kivilahti, Samuli Tuomola, Danilo Lemos for creating this game, porting it to SDL and finally to SDL2 and making it available for free. Also thanks to Cebion for the packaging for portmaster.
> Add Pekka Kana 2

- ports.md
New Port Hijinx
Hijinx
Instructions: Hijinx files are already included and ready to go. Just start the game from Ports in the Emulationstation menu.
Notes: Thanks to John Gabriel (https://bitbucket.org/JohnGabrielUK/hijinx/)  for creating this game and making it available for free. Also thanks to Cebion for the packaging for portmaster.
> Add Hijinx Port

- ports.md
New Port for Nova Pinball
URL: https://github.com/wesleywerner/nova-pinball
Nova Pinball
Instructions: Game files are already included and ready to go. Just start the game from Ports in the Emulationstation menu.
Notes: Thanks to Wesley Werner  for creating this game and making it available for free and Eric Ahnell for the Löve 11.2 Port. Also thanks to Cebion for the packaging for portmaster.
Tested on AmberELEC RG552, 351V, uOS, ArkOS
> Add Nova Pinball

- ports.md
New Port for xkcd Hoverboard
URL: https://github.com/AMDmi3/hoverboard-sdl
xkcd Hoverboard
Instructions: All files are included and game is ready to play.
Notes: Thanks to Dmitry Marakasov for this native port of the game by Randall Munroe, thanks to Bamboozler for packing for Portmaster and thanks to the Portmaster team for testing.
Tested on ArkOS, Jelos and AmberELEC
> Add xkcd Hoverboard

- ports.md
New Port for Plaque Attack Remake
URL: https://github.com/Keyband/dentaldefense
Plaque Attack Remake
Instructions: To run the game start PlaqueAttackRemake.sh from your ports folder. To Force a particular version rename the desired one in the installation folder as PlaqueAttackRemake.zip and delete the other one, then boot.
Notes: A big thanks to Escada Games for creating the game and sharing the source code. And, of course, a huge thanks to the Portmaster Team for testing!
Tested on Rg353,RG351v and rg552 on Amberelec, Arkos and Jelos
> Add Plaque Attack Remake

- ports.md
New Port for Dome Romantik
URL:  https://bippinbits.itch.io/dome-romantik
Dome Romantik
Instructions: Dome Romantik files are already included and ready to go. To Force a particular version rename the desired one in the installation folder as domeromantik-linux.zip (same for the gptk file) and delete the others ones, then boot
Notes: A heartfelt thank you goes out to René from Bippinbits for granting authorization for this port and its distribution. And obviously a big thanks at the portmaster team for testing it.
Tested on Rg353,rg351v and Rg552 on Arkos. Jelos and Amberelec
> Add Dome Romantik

- ports.md
New (Updated) Port for Tile World based on the handheld version by senquack.
URL: Handheld version by senquack: https://github.com/senquack/tileworld-for-handhelds
Tile World written originally by Brian Raiter: https://www.muppetlabs.com/~breadbox/software/tworld/
Tile World
Instructions: To play the original Chip's Challenge levels, copy 'chips.dat' into 'ports/tileworld/data' and make sure it's lowercase.
Notes: Modified source code and graphics to 640x480 (was 320x240 for GP2X & GCW0), fixed save system bug and sprite drawing by AAK (Slayer366).  Custom "Tilebyte" game fonts by JRK (Budah).
Tested on ArkOS, AmberElec, JelOS, RG351P, RG353P (should also work on other platform and OS combinations).
> TileWorld now HandHeld edition.

- ports.md
New Port for Wizznic!
URL: https://github.com/DusteDdk/Wizznic
Wizznic!
Instructions: All files are included and game is ready to play.
Notes:  Thanks to DusteDdk for making this game, Bamboozler for packaging to Portmaster and the Portmaster testers for testing.
Tested on AmberELEC, ArkOS and Jelos
> Add Wizznic!

- ports.md
New Port for Beat2x
URL: https://github.com/christopher-roelofs/beat2x
Beat2x
Instructions: All files are included and ready to play.
Notes: Thanks to miq01 and Zenzuke for the game.
Tested on ArkOS, AmberELEC and uOS
> Add beat2x

- ports.md
New Port for OpenMRac
URL: https://github.com/Franticware/OpenMRac
OpenMRac
Instructions: Game files are already included and ready to go. Just start the game from Ports in the Emulationstation menu.
Notes: Thanks to Franticware for creating this game and making it available for free and Vojtěch Salajka for the Programming. Also thanks to Cebion for the packaging for portmaster.
Tested on AmberELEC RG552, 351V, uOS, ArkOS, JELOS, 320x480, 640x480, 1920x1152
> Add OpenMRac

- .github/workflows/release.yaml
Changed github/action so that the release is done as a draft until all the ports/files are updated to stop PortMaster from breaking as per @pkegg's recommendation.
Made it so editing the README no longer causes a new release to occur.
Tested on: VCMI on ArkOS, AmberELEC, uOS and JELOS on 351v and 353v
> Updated VCMI, changed github release code.

- markdown/cceleste.md
- markdown/devilutionx.md
- markdown/f1race.md
- markdown/nonny.md
- markdown/znax.md
add markdown folder that will be referenced in the "additional details" section of the details page for the port wiki
> add markdown forlder
