christianhaitian/PortMaster

ports.md

Finally got the latest openxcom packaged up and ready to go.  This is my first PR, hope everything works right.

Add OpenXcom Extended port (version 7.5.3)

---

ports.md

Wiki:
Mighty Mike (RG552 JelOS Only!) Instructions: Mighty Mike files are already included and ready to go. Just start Mighty Mike from Ports in the emulationstation menu. Currently only runs on the RG552 with Jelos installed.
Notes: Thanks to Pangea Software for creating the game and publicly releasing the game files. Thanks to Jorio (https://github.com/jorio/MightyMike) for porting the game engine to various platforms.
Nanosaur (RG552 JelOS Only!) Instructions: Nanosaur files are already included and ready to go. Just start Nanosaur from Ports in the emulationstation menu. Currently only runs on the RG552 with Jelos installed.
Notes: Thanks to Pangea Software for creating the game and publicly releasing the game files. Thanks to Jorio (https://github.com/jorio/nanosaur) for porting the …

Adding Nanosaur and Mighty Mike

---

PortMaster/PortMaster.sh
PortMaster/control.txt

Adds support for UnofficialOS builds.

Support UnofficialOS

---

ports.md

[GemRB](https://gemrb.org) (Game Engine Made with preRendered Background) is a portable open-source reimplementation of the Infinity Engine that underpinned Baldur's Gate, Icewind Dale and Planescape: Torment.
To play various GemRB compatible games you need to copy over the game files into `ports/gemrb/games` into their own directory. For example you would install the **Baldur's Gate** game files into `ports/gemrb/games/bg1` directory. Currently EE versions are not 100% compatible.
[GemRB](https://gemrb.org) is a portable open-source reimplementation of the Infinity Engine. A few changes were made to the underlying engine to run, those changes were merged upstream.
This currently has been verified to run on on RG353P/V/M, RG351V/MP, RG552 on ArkOS/AmberElec/UnofficialOS.

Added GemRB port.

---

ports.md

Enigma
======
Enigma is a unique puzzle game, with influences from almost every game
genre.  Your objective is easily explained: you control a small black
marble with your mouse and have to find and uncover all pairs of
identical Oxyd stones in each landscape.  Simple? Yes.  Easy? It would
be, if it weren't for hidden traps, vast mazes, insurmountable
obstacles and innumerable puzzles blocking your direct way to the Oxyd
stones... If you like puzzle games and have a steady hand, Enigma's
more than 1000 original levels will probably keep you busy for hours
on end.
Enigma is developed by a small group of volunteers, and help is always
appreciated.  If you like Enigma and want to contribute to its future,
you are welcome to join us on our development mailing list at …

add Enigma

---

ports.md

add missing porter and locat properties

add missing porter and locat properties

---

ports.md

A port of Axiom Verge, an awesome metroidvania 2D platformer.
Make sure you have "mono-6.12.0.122-aarch64.squashfs" in the Portmaster/libs folder
Use the Epic Games version!!!
Copy the "Content" and "Log" folders here
Copy Following Files from Axiom Verge root here:
AsyncBridge.dll
Axiom Verge.bmp
Axiom Verge.exe
AxiomVerge.exe.config
AxiomVerge.pdb
changelog.txt
CrowdControl.Client.Binary.dll
FAudio.dll
FNA.dll.config
FNA3d.dll
gamecontrollerdb.txt
I18N.dll
I18N.West.dll
JetBrains.Annotations.dll
libogg.dll
libtheorafile.dll
libvorbis.dll
libvorbisfile.dll
log4net.dll
log4net.xml
LOG4NETLICENSE.txt
LogAppender.xml
MojoShader.dll
Newtonsoft.Json.dll
Newtonsoft.Json.xml
SDL2.dll
SDL2-2.0.3.bak
soft_oal.dll
websocket-sharp.dll
websocket-sharp.xml
Tested successfully on Arkos, JELOS, …

Axiom Verge

---

ports.md

Neverball and Neverputt
========
**Neverball**
Tilt the floor to roll a ball through an obstacle course within the given time. If the ball falls or time expires, a ball is lost.
Collect coins to unlock the exit and earn extra balls. Red coins are worth 5. Blue coins are worth 10. A ball is awarded for 100 coins.
**Neverputt**
A hot-seat multiplayer miniature golf game, built on the physics and graphics engine of Neverball.
Developer: Neverball developers
URL: https://github.com/Neverball/neverball
All files are included for both games and it is ready to run.
Tested on ArkOS, uOS and AmberELEC.
Thanks to PortMaster testers.
**CONTROLS**
Neverball
Select = ESC
Start = Enter
Dpad and Left stick = movement
Right stick left/ right L/R = look
A = Select
B = Back/esc
Neverputt
Dpad and Left …

add Neverball and Neverputt

---

ports.md

New Port Eity 
Eity 
Instructions: Eity files are already included and ready to go. Just start the game from Ports in the Emulationstation menu.
Notes: Thanks to Eemeli Mark (https://github.com/TheJeme/Eity) for creating this game and making it available for free. Also thanks to Cebion for the packaging for portmaster.

Add Eity Rhytm Game

---

ports.md

Thermomorph
Instructions:  Thermomorph files are already included and ready to go. Just start the game from Ports in the Emulationstation menu.
Notes: Thanks to Varun Ramesh (https://github.com/rameshvarun/thermomorph) for creating this game and making it available for free. Also thanks to Cebion for the packaging for portmaster.

Add Thermomorph

---

docs/pull_request_template.md

Adding a template for new pull requests

Add PR Template

---

ports.md

New Port for LBreakoutHD
LBreakoutHD
Instructions: All files are inclluded and ready to play.
Notes: Thanks to Michael Speck for creating LBreakout2 and LBreakoutHD, Bamboozler for packaging the game for PortMaster and to the PortMaster team for testing.
Tested on Arkos, uOS and AmberELEC

Add LBreakoutHD

---

docs/pull_request_template.md

Add a URL entry in PR template.

Add source url to PR template

---

ports.md

New Port for Retro Time
URL: https://github.com/joyrider3774/RetroTime
Retro Time
Instructions: All files are included and game is ready to play.
Notes: Thanks to Willems Davy for making this game, Bamboozler for porting to Portmaster and the Portmaster team for testing.
Tested on ArkOS, uOS and AmberELEC

Add Retro Time

---

ports.md

New Port for Me and My Shadow
URL: https://github.com/acmepjz/meandmyshadow
Me and My Shadow
Instructions: All files are included and game is ready to play. Addons should be available to download after you restart the game the first time.
Notes:  Thanks to Jz Pan and other contributers to this game, Bamboozler for packaging for Portmaster and the Portmaster team for testing.
Tested on ArkOS, uOS and AmberELEC

Add Me and My Shadow

---

ports.md

New Port for SuperTuxKart
URL: https://supertuxkart.net/Main_Page
SuperTuxKart
Instructions: All files are included and game is ready to play.
Notes: Thanks to the SuperTuxKart team and contributors , Bamboozler for packing for Portmaster and the Portmaster team for testing.
Tested on ArkOS, uOS and AmberELEC

Add SuperTuxKart

---

ports.md

New Port for Planet Waves
URL: https://github.com/Tekkenfede/planet-waves-handhelds
Planet Waves
Instructions: All files included. Run PlanetWaves.sh and Play
Notes: A big thanks to Escada Games for creating the game and sharing the source code. And, of course, a huge thanks to the Portmaster Team for testing!
Tested on Rg353,RG351v and rg552 on Amberelec, Arkos and Jelos

Add Planet Waves

---

ports.md

New Port for Farmner
URL: (https://jaydensippy.itch.io/farmner)
Farmner
Instructions: The game files are already included and ready to go. Suggested for rg552 to force a lower resolution and speed up the mouse in the gpkt. 
Notes: A Special thanks at the game dev and at the portmaster community for testing
Tested on Jelos, Arkos, Amber Elec on rg353 and rg552. Can have low perfomance on rk3326 devices

Add Farmner

---

ports.md

**New Port for Curse of Issyos**
URL: (http://locomalito.com/curse_of_issyos.php)
Curse of Issyos
Instructions: To succesfully boot the game copy the data.win file into the gamedata folder, then boot the game from Coi.sh.
**New Port for ZeroRanger**
URL: (https://system-erasure.itch.io/zeroranger)
ZeroRanger
Instructions: To start the game copy the data.win/game.unx and all the ogg files inside the gamedata folder, then boot the game from the ports menu on your device.
**New Port for VA-11_Hall-A:Cyberpunk_Bartender_Action **
URL: (https://sukebangames.itch.io/valhalla-bar)
VA-11_Hall-A:Cyberpunk_Bartender_Action
Instructions: To boot copy the data.win/game.unx files and all the folder inside the gamedata folder and then boot the game from Valhalla.sh
Notes: Thanks at Johhny on Flames for …

Add Curse of Issyos, ZeroRanger and VA-11 Hall-A: Cyberpunk Bartender Action

---

ports.md

New Port for Chip N Dale Remastered
https://forum.gamemaker.io/index.php?threads/chip-dale-remastered-open-source.1652/ 
Instructions: Ready To run, Just launch CHIPNDALE.sh 
Notes: A bit thanks at the Portmaster community to test the game, and at the other porting communities, that with their existing ports gave me a faster and more stable base on which work.
Tested on 
[x] rg351p amberelec
[x] rg353m arkos
[x] rg353v jelos 
[x] rg353vs arkos & jelos
[x] oga arkos
[x] rg503
[x] x55 
New Port for Megaman Rock N Roll
https://dennisengelhard.com/rock-n-roll/
Instructions: Ready To run, Just launch Megaman.sh 
Notes: A bit thanks at the Portmaster community to test the game, and at the original developer for granting us the permission to distribute this game as ready to play.
Tested on 
[x] …

Added Chip N Dale, Megaman Rock N Roll and Beat of The Pixel Heat

---

ports.md

"This has been tested with Linux 64-bit, Dec 30 2022 release"
-->
"This has been tested with Windows 64-bit, Dec 30 2022 release"

Correct DROID7 typo

---

.github/workflows/pull_request.yaml

I missed a few things, this should fix them hopefully.

Fix bugs with pr-check

---

.github/workflows/release.yaml

two port sources and simplifying things on harbourmaster.

changed github/workflow to fetch the runtimes, removing the need for 

---

markdown/quakespasm.md

Made Quakespasm.md easier to read (suggested edit by Croelofs)

Update Quakespasm.md per Croelofs

---

markdown/descent.md
markdown/descent2.md

This is sort of an urgent pull request as I just found the `Descent.sh` and `Descent 2.sh` files inside the zip were likely in the wrong encoding format (CR LF instead of LF) and therefore would not run. I have corrected the issue.
I have also updated the markdown readme files, which I neglected to do in prior updates.

Patch Descent ports

---

markdown/luck.be.a.landlord.md

Controls table rendering incorrectly http://portmaster.games/detail.html?name=luck.be.a.landlord
Hopefully, this fixes it.

Update markdown Luck be a Landlord table (rendering wacky on website)
